# Generated by Django 2.0.2 on 2018-02-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='shortcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
