# Generated by Django 2.0.2 on 2018-02-21 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_urlshortner_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
