# Generated by Django 2.0.2 on 2018-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_urlshortner_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='shortcode',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
