# Generated by Django 2.0.1 on 2018-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180220_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='http://domain.com/link1', max_length=2000, verbose_name='Url')),
            ],
        ),
        migrations.RenameField(
            model_name='projekturl',
            old_name='url',
            new_name='projekt',
        ),
        migrations.AddField(
            model_name='url',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProjektUrl'),
        ),
    ]
