# Generated by Django 2.0.2 on 2018-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180221_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
